### PR TITLE
Edit README.md

### PR DESCRIPTION
**Pull request by AnotherButler**
Copy edit file, mostly for branding and spelling.

### CODE REVIEW

**Comment by AnotherButler** [comment]
@TuomoHautamaki Could you please review this or tag someone else as a reviewer?

**Comment by SeppoTakalo** [comment]
Looks good. I don't spot anything to change.

**Comment by mikter** [comment]
@mikaleppanen please check as this is change that conflicts your modifications for pull request after MbedOS release

**Comment by AnotherButler** [comment]
Who can merge this?

**Pull request merged**
