### PR TITLE
Add enabling/disabling MLD proxying to upstream

### PR DESCRIPTION
**Pull request by miklau01**
Added enabling/disabling of proxying MLD messages to upstream to thread_br_conn_handler_ethernet_connection_update(().

### CODE REVIEW

**Comment by miklau01** [comment]
@artokin @kjbracey-arm Could you please review?

**Comment by kjbracey-arm** [comment]
Feels to me that this should be a config option for a border router tasklet. If this tasklet is using the config system, maybe slot it into there, defaulting on.

**Comment by kjbracey-arm** [comment]
Oh, and do you want to expose the full-forwarding scope change too?

**Comment by miklau01** [comment]
@kjbracey-arm Added config option, does it look OK to you? About full-forwarding scope change, discussed with @mikter about it and he suggested it would be best to enable it by default (remove the disabling of multicast forwarding from nanostack thread bootstrap) and disable it where wanted (thread-bbr-extension)

**Pull request merged**
