### PR TITLE
Remove default mbed app json

### PR DESCRIPTION
**Pull request by MarceloSalazar**
Proposal to remove default `mbed_app.json` and tweak documentation to avoid confusion on how to configure the app.

@SeppoTakalo

### CODE REVIEW

**Comment by SeppoTakalo** [comment]
CC: @artokin 

I don't really agree.
By default, the application should build.

For those who we cannot trust to modify the configuration file, we cannot trust them to be able to run this application at all.

Mesh configuration requires knowledge of the existing network and technology. I cannot assume any of the example configuration files to be suitable in any real world scenarios.
Nobody can expect network routers (for example WiFi router) to work out of box without any configuration, this is same here. This is an IPv6 router, you need to learn its configuration mechanism to be able to run it properly.
I think that providing any sort of default configuration files for user is basically setting the bar too low. When users just try to run this without knowing what it is, it leads to lots to queries for us that  has nothing to do with the application itself but to the network they try to run it.

**Comment by adbridge** [comment]
@MarceloSalazar Can you respond to Seppo's comments please ?

**Comment by MarceloSalazar** [comment]
Hi @SeppoTakalo 

Thanks for the sharing your thoughts. With this PR, my intention is to simplify the UX for users that are evaluating the application and avoid conflicting messages on what is the default configuration actually doing.

Once first time users have something working, they would need to be looking at advanced configurations and documentation, but for sure not from the very beginning. This is the reason why we wouldn't want them to edit json files and deal with things they may not be very familiar.

We're looking to align all examples that have the same problem (mesh-minimal, client, and potentially wifi), not just this BR app, hence my comments are *generic* to this kind of configurable applications.

It's important that we lower the entry barrier for those that want to get started and learn. *Many* of them (myself included) just want to get devices connected, show demos and start prototyping. We don't need to complicate things at the beginning. There would be advanced guides and tutorials for other cool stuff.

> By default, the application should build.

This is my main concern, which configuration are we using by default?
As you know, there is a variety of network and shield configurations (6lowpan, thread, wifi, etc, etc).
The mbed_app.json file seems to be a copy of another file from the config directory.

Perhaps we can discuss this with @senthilr , @JanneKiiskila and @yogpan01

**Comment by SeppoTakalo** [comment]
After a second thought, I'm inclined to agree with the removal.
In the backround I did worry about the CI results, but seems that we also use those configuration files from `configs/` in the CI job. Therefore the one in the root folder is actually untested. Which is also another reason to drop it.

@artokin @mikter If you agree with this, please merge in.

From my point of view, the configuration phase is sufficiently well documented so this change is OK.

**Comment by JanneKiiskila** [comment]
I've been having this kind of debate myself as well, and I did actually consider once removing the default `mbed_app.json` completely on our side as well. The fact is that if anyone needs to modify it, you have a trackable git file (changes to an existing one) and further updates/rebases just get more confused. It would be easier from git usage point of view if you didn't have it, you would just copy the "most right" one from configs/*.json to be your mbed_app.json and then add it as your own trackable file. Further git merges/rebases would be easier, as there would *never* be a merge conflict with that file.

**Comment by JanneKiiskila** [comment]
@teetak01  raised a good point - one potential issue relies with the `.mbedignore` files. It would be so good to have the ability to define a `.mbedignore` file to use per config, so that choosing the profile would automatically (from end-user point of view) pick the right `.mbedignore` file as well.

**Comment by SeppoTakalo** [comment]
@JanneKiiskila 
If you need `.mbedignore` file, something is wrong there.

Traditionally, we needed it because we included some drivers that don't compile on all platforms.
Is this still the case, and if it is, are those problems reported to Mbed OS?

**Comment by JanneKiiskila** [comment]
Yes, we still have those.

**Comment by MarceloSalazar** [comment]
I agree, there are a few things that need clarification first.

In addition, we need to define behavior when no mbed_app.json is updated. E.g. show a meaningful error message, instead of showing an error in the code.

We've been having good discussions but I don't think we are ready to merge this right now.

**Comment by JanneKiiskila** [comment]
Related mbed-cli issue ref: https://github.com/ARMmbed/mbed-cli/issues/586

**Pull request closed without merging**
