### PR TITLE
Update configuration

### PR DESCRIPTION
**Pull request by artokin**
-Use ETH instead of EMAC
-Use malloc for nanostack heap for Thread
-Change Thread PSKd to ABCDEFGH

### CODE REVIEW

**Comment by artokin** [comment]
@kjbracey-arm , @SeppoTakalo

**Comment by MarceloSalazar** [comment]
Is this something we should evaluate during OOB?

Bear in mind we're currently using the mbed-os-5.9.0-oob branch and preparing for the release this week. If you think these are important changes, then please consider changing the base branch.

**Comment by kjbracey-arm** [comment]
#108 should also be taken into the oob branch. Can I go ahead and do that?

**Comment by kjbracey-arm** [comment]
Actually, Arto's already done it - missed it.

**Pull request merged**
